version: "3.3"
services:
  web111:
        container_name: web111
        image: nginxmine:new
        ports:
          - "8081:8081"
        volumes:
          - Newvol01:/www
  web222:
        container_name: web222
        image: apachemine:new
        ports:
          - "8082:8082"
        volumes:
          - Newvol01:/www

volumes:
  Newvol01:
