version: "3.3"
services:
  web111:
        container_name: web111
        image: nginxmine:new
        deploy:
            resources:
                limits:
                  cpus: '0.50'
                  memory: 512M               
        networks:
          netnginx:
            ipv4_address: 172.19.0.2
        ports:
          - "8081:8081"
        volumes:
          - Newvol01:/www
  web222:
        container_name: web222
        image: apachemine:new
        deploy:
            resources:
                limits:
                  cpus: '0.50'
                  memory: 512M
        networks:
          netnginx:
            ipv4_address: 172.25.0.2
        networks:
          - netapache
        ports:
          - "8082:8082"
        volumes:
          - Newvol01:/www
networks:
  netnginx:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
  netapache:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
volumes:
  Newvol01:
