version: "3.9"
services:
  #nginxmy:
  #      build: ./nginx/
  #      image: nginxmy
  #      ports:
  #        - "8081:8081"
  #      volumes:
  #        - volume01:/www:rw
  #apachemy:
  #      build: ./apache/
  #      image: apachemy
  #      ports:
  #        - "8082:8082"
  #      volumes:
  #        - volume01:/www:rw

  web111:
        container_name: web111
        image: nginxmy
        volumes:
          - volume01:/www:rw
        ports:
          - "8081:8081"
  web222:
        container_name: web222
        image: apachemy
        ports:
          - "8082:8082"
        volumes:
          - volume01:/www:rw

volumes:
  volume01:
    external: true
