version: "3.9"
services:
  web111:
        build: ./nginx/
        image: nginxmy
        ports:
          - "8081:8081"
        volumes:
          - volume01:/www:rw
  web222:
        build: ./apache/
        image: apachemy
        ports:
          - "8082:8082"
        volumes:
          - volume01:/www:rw
volumes:
  volume01:
    external: true
