version: "3.9"
services:
  web1:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/code
      - volume01:/var/log
    links:
      - redis
  web2:
    build: .
    ports:
      - "8081:81"
    volumes:
      - .:/code
      - volume01:/var/log
    links:
      - redis
volumes:
  volume01: {}
