version: "3.9"
services:
  web1:
    build: .
    ports:
      - "5000:80"
    volumes:
      - .:/code
      - volume01:/var/log
    links:
      - redis
  web2:
    build: .
    ports:
      - "5001:80"
    volumes:
      - .:/code
      - volume01:/var/log
    links:
      - redis
volumes:
  volume01: {}
