version: "3.3"
services:
  web111:
        container_name: web111
        image: nginxmine:new
        deploy:
            resources:
                limits:
                  cpus: '0.50'
                  memory: 512M               
        networks:
          - netnginx
        ports:
          - "8081:8081"
        volumes:
          - Newvol01:/www
  web222:
        container_name: web222
        image: apachemine:new
        deploy:
            resources:
                limits:
                  cpus: '0.50'
                  memory: 512M
        networks:
          - netapache
        ports:
          - "8082:8082"
        volumes:
          - Newvol01:/www
networks:
  netnginx:
  netapache:

volumes:
  Newvol01:
